# Generated by Django 3.2.6 on 2021-08-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='profile-images/default.png', upload_to='profile-images/%y/%m/%d/')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('whatsapp', models.CharField(blank=True, max_length=25, null=True, verbose_name='Whatsapp')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'blog_account',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricão')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizacões')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=1, null=True, verbose_name='Estrelas')),
                ('like', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Gostei')),
                ('unlike', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Não gostei')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Rascunho'), (2, 'Publicado')], default=0)),
                ('enable_comments', models.BooleanField(default=False, verbose_name='Habilitar comentários')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_posts', to='blog.account', verbose_name='Conta')),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Post',
                'db_table': 'blog_post',
                'ordering': ['-created_on'],
            },
        ),
    ]
