# Generated by Django 3.2.5 on 2021-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddField(
            model_name='post',
            name='image_blog',
            field=models.ImageField(default='blog-images/default.jpg', upload_to='blog-images/%y/%m/%d/'),
        ),
    ]
